import type { CapabilityLeaseBroker } from "./capability-lease-broker.ts";
import type { CapabilityPolicyAuthorizer } from "./capability-policy-authorizer.ts";
import type { CapabilityReceiptSink } from "./capability-receipt-sink.ts";
import type { FilesRefResolver } from "./files-ref-resolver.ts";
import type { PullRequestOutputPort } from "./pull-request-output-port.ts";
import type {
  CapabilityLeaseReceipt,
  CapabilityLeaseRequest,
  CapabilityLeaseResult,
  PullRequestReceipt,
} from "./schemas.ts";
import type { SecretMaterialStore } from "./secret-material-store.ts";

export interface PayloadBoundCapabilityLeaseBrokerPorts {
  authorizer: CapabilityPolicyAuthorizer;
  filesRefResolver: FilesRefResolver;
  pullRequestOutput: PullRequestOutputPort;
  receiptSink: CapabilityReceiptSink;
  secretMaterialStore: SecretMaterialStore;
}

export const buildPrototypePrBody = (input: CapabilityLeaseRequest): string =>
  [
    "Generated by `cloud-capability-lease-broker-spike`.",
    "",
    "## Capability lease",
    "",
    `- run: \`${input.runId}\``,
    `- capability: \`${input.capability}\``,
    `- filesRef: \`${input.filesRef}\``,
    `- payloadHash: \`${input.payloadHash}\``,
    "",
    "Root secret material and GitHub installation tokens stayed inside the broker boundary.",
  ].join("\n");

export class PayloadBoundCapabilityLeaseBroker implements CapabilityLeaseBroker {
  private readonly ports: PayloadBoundCapabilityLeaseBrokerPorts;

  constructor(ports: PayloadBoundCapabilityLeaseBrokerPorts) {
    this.ports = ports;
  }

  async requestCapability(
    input: CapabilityLeaseRequest
  ): Promise<CapabilityLeaseResult> {
    const decision = await this.ports.authorizer.authorize(input);
    if (decision.status === "denied") {
      return { blocker: decision.blocker, status: "blocked" };
    }

    const resolvedFiles = await this.ports.filesRefResolver.resolve(
      input.filesRef
    );
    if (resolvedFiles.payloadHash !== input.payloadHash) {
      return {
        blocker: {
          code: "payload_hash_mismatch",
          message:
            "Resolved filesRef payload hash did not match the approved capability envelope.",
          redacted: true,
        },
        status: "blocked",
      };
    }

    let pullRequestReceipt: PullRequestReceipt;
    try {
      pullRequestReceipt =
        await this.ports.secretMaterialStore.withSecretMaterial(
          {
            capability: input.capability,
            policyId: decision.policyId,
            purpose: "execute-payload-bound-capability",
            runId: input.runId,
            secretRef: input.secretRef,
          },
          (signingHandle) =>
            this.ports.pullRequestOutput.openPullRequest(
              {
                branch: input.branch,
                files: resolvedFiles.files,
                filesRef: input.filesRef,
                payloadHash: input.payloadHash,
                prBody: buildPrototypePrBody(input),
                prBodyHash: input.prBodyHash,
                prTitle: input.prTitle,
                repo: input.repo,
                runId: input.runId,
              },
              signingHandle
            )
        );
    } catch (error) {
      if (error instanceof Error && error.message === "secret_unavailable") {
        return {
          blocker: {
            code: "secret_unavailable",
            message:
              "Secret material was unavailable inside the trusted broker boundary.",
            redacted: true,
          },
          status: "blocked",
        };
      }
      throw error;
    }

    const receipt: CapabilityLeaseReceipt = {
      actor: input.actor,
      branch: pullRequestReceipt.branch,
      capability: input.capability,
      capabilityRef: `capability:${input.runId}:${input.capability}:${input.payloadHash.slice(0, 12)}`,
      checks: [
        {
          id: "policy-authorized",
          status: "passed",
          summary: `Policy ${decision.policyId} approved the payload-bound capability envelope.`,
        },
        {
          id: "payload-hash-matched",
          status: "passed",
          summary: "Resolved filesRef matched the approved payload hash.",
        },
        {
          id: "broker-executed-output",
          status: "passed",
          summary:
            "Pull request output was executed by the broker path without handing a token to the workflow.",
        },
      ],
      commitSha: pullRequestReceipt.commitSha,
      expiresAt: decision.expiresAt,
      payloadHash: input.payloadHash,
      policyId: decision.policyId,
      prUrl: pullRequestReceipt.prUrl,
      redacted: true,
      repo: input.repo,
      runId: input.runId,
      secretRef: input.secretRef,
    };

    await this.ports.receiptSink.record(receipt);
    return { receipt, status: "executed" };
  }
}
