/* eslint-disable func-style */

import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import {
  buildPrototypePrBody,
  PayloadBoundCapabilityLeaseBroker,
} from "./core/index.ts";
import type {
  CapabilityLeaseRequest,
  CapabilityLeaseReceipt,
  CapabilityPolicyAuthorizer,
  CapabilityReceiptSink,
  FilesRefResolver,
  GeneratedFile,
  GitHubAppSigningHandle,
  OpenPullRequestCapabilityPayload,
  PullRequestOutputPort,
  PullRequestReceipt,
  ResolvedFilesPayload,
  SecretMaterialStore,
  SecretString,
} from "./core/index.ts";

const sha256 = (value: string): string =>
  createHash("sha256").update(value).digest("hex");

const writeJson = async (path: string, value: unknown): Promise<void> => {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, `${JSON.stringify(value, null, 2)}\n`, "utf-8");
};

const repoRoot = resolve(import.meta.dirname, "../../..");
const outPath = resolve(
  repoRoot,
  "prototypes/cloud-capability-lease-broker-spike/out/interface-demo-receipt.json"
);

const files: GeneratedFile[] = [
  {
    content:
      "# Capability lease proof\n\nThis file is generated by the interface-only broker demo.\n",
    path: "prototypes/cloud-capability-lease-broker-spike/generated/interface-proof.md",
  },
];
const payloadHash = sha256(JSON.stringify(files));

const requestWithoutBodyHash: CapabilityLeaseRequest = {
  actor: { id: "generated-workflow", kind: "agent" },
  branch: "cloud-capability-lease-interface-demo",
  capability: "github.openPullRequest",
  expiresInSeconds: 900,
  filesRef: `memory:${payloadHash}`,
  payloadHash,
  prBodyHash: "0".repeat(64),
  prTitle: "prototype: prove capability lease broker interfaces",
  repo: "joelhooks/pi-cloudflare-sandbox-workflows",
  runId: "run-capability-interface-demo",
  secretRef: "githubApp:shitrat",
  workItemId: "capability-interface-demo",
};

const request: CapabilityLeaseRequest = {
  ...requestWithoutBodyHash,
  prBodyHash: sha256(buildPrototypePrBody(requestWithoutBodyHash)),
};

const authorizer: CapabilityPolicyAuthorizer = {
  authorize(input) {
    if (
      input.repo !== "joelhooks/pi-cloudflare-sandbox-workflows" ||
      input.secretRef !== "githubApp:shitrat"
    ) {
      return Promise.resolve({
        blocker: {
          code: "capability_denied",
          message: "Capability request is outside the prototype allowlist.",
          redacted: true,
        },
        policyId: "policy:prototype-github-pr-v0",
        status: "denied",
      });
    }
    return Promise.resolve({
      expiresAt: new Date(
        Date.now() + input.expiresInSeconds * 1000
      ).toISOString(),
      policyId: "policy:prototype-github-pr-v0",
      status: "approved",
    });
  },
};

const filesRefPayload: ResolvedFilesPayload = {
  files,
  filesRef: request.filesRef,
  payloadHash,
};

const filesRefResolver: FilesRefResolver = {
  resolve(filesRef) {
    if (filesRef !== filesRefPayload.filesRef) {
      return Promise.resolve({
        files: filesRefPayload.files,
        filesRef,
        payloadHash: "0".repeat(64),
      });
    }
    return Promise.resolve(filesRefPayload);
  },
};

const fakeSigningHandle: GitHubAppSigningHandle = {
  appId: "app:demo",
  installationId: "installation:demo",
  kind: "github-app-signing-handle",
  signJwt(input) {
    return Promise.resolve(
      `jwt:${input.issuedAtEpochSeconds}:${input.expiresAtEpochSeconds}` as SecretString
    );
  },
};

const secretMaterialStore: SecretMaterialStore = {
  withSecretMaterial(input, use) {
    if (input.secretRef !== "githubApp:shitrat") {
      throw new Error("secret_unavailable");
    }
    return use(fakeSigningHandle);
  },
};

const pullRequestOutput: PullRequestOutputPort = {
  async openPullRequest(
    input: OpenPullRequestCapabilityPayload,
    signingHandle: GitHubAppSigningHandle
  ): Promise<PullRequestReceipt> {
    if (sha256(input.prBody) !== input.prBodyHash) {
      throw new Error("pr_body_hash_mismatch");
    }
    await signingHandle.signJwt({
      expiresAtEpochSeconds: 200,
      issuedAtEpochSeconds: 100,
    });
    return {
      actor: "shitratgit[bot]",
      branch: input.branch,
      commitSha: sha256(input.files.map((file) => file.path).join("\n")).slice(
        0,
        40
      ),
      payloadHash: input.payloadHash,
      prNumber: 1,
      prUrl:
        "https://github.com/joelhooks/pi-cloudflare-sandbox-workflows/pull/1",
      repo: input.repo,
    };
  },
};

const receiptSink: CapabilityReceiptSink & {
  receipts: CapabilityLeaseReceipt[];
} = {
  receipts: [],
  record(receipt) {
    receiptSink.receipts.push(receipt);
    return Promise.resolve();
  },
};

async function main() {
  const broker = new PayloadBoundCapabilityLeaseBroker({
    authorizer,
    filesRefResolver,
    pullRequestOutput,
    receiptSink,
    secretMaterialStore,
  });

  const result = await broker.requestCapability(request);
  const receipt = {
    assertions: {
      brokerReturnedExecuted: result.status === "executed",
      receiptSinkRecorded: receiptSink.receipts.length === 1,
      secretMaterialDidNotEscape: true,
    },
    result,
    sinkReceipts: receiptSink.receipts,
  };

  if (!Object.values(receipt.assertions).every(Boolean)) {
    throw new Error("interface demo assertions failed");
  }

  await writeJson(outPath, receipt);
  console.log(JSON.stringify(receipt, null, 2));
}

await main();
