import type {
  ReviewSurfaceObservabilitySignal,
  ReviewSurfaceStructuredLogField,
} from "./schemas.ts";

export const workflowObservabilityRequiredSignals = [
  "structured-high-cardinality-logs",
  "runtime-event-log",
  "trace-spans",
  "metrics",
  "cost-token-accounting",
  "sandbox-accounting",
  "capability-lease-receipts",
  "agent-readable-observability-pack",
  "status-projection",
  "redaction-policy",
] as const satisfies readonly ReviewSurfaceObservabilitySignal[];

export const workflowObservabilityHighCardinalityFields = [
  "runId",
  "workItemId",
  "capsuleId",
  "actorId",
  "packageId",
  "packageVersion",
  "artifactRepo",
  "artifactRef",
  "artifactCommitSha",
  "laneId",
  "laneKind",
  "laneRuntime",
  "sandboxRef",
  "admissionId",
  "stepId",
  "stepKind",
  "capability",
  "leaseId",
  "resourceRef",
  "payloadHash",
  "verifierResultId",
  "reviewSurfaceId",
  "blockerCode",
  "traceId",
  "spanId",
  "durationMs",
  "tokenCount",
  "costEstimate",
  "projectionSink",
  "projectionStatus",
] as const satisfies readonly ReviewSurfaceStructuredLogField[];
